###libraries
#install.packages("ggplot2")
library(ggplot2)
#install.packages("dplyr")
library(dplyr)
#install.packages("tidyverse")
library(tidyverse)
#install.packages("dslabs")
library (dslabs)
#install.packages("gtsummary")
library(gtsummary)
#install.packages("writexl")
library(writexl)
#install.packages("ggsurvfit")
library(ggsurvfit)
#install.packages("stringr")
library(stringr)
#install.packages("survminer")
library(survminer)
#install.packages("ggpubr")
library(ggpubr)

if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
library(BiocManager)

BiocManager::install("GSVA")
library(GSVA)